obstacle_range: 2.5
raytrace_range: 3.0
#robot_radius: 0.32
footprint: [[0.3,0.09], [0.3,-0.09], [0.1,-0.22],[-0.08,-0.22],[-0.08,0.22],[0.1,0.22]]

max_obstacle_height: 0.6
min_obstacle_height: 0.0

obstacle_layer:
  observation_sources: laser_scan_sensor
  laser_scan_sensor:
    data_type: LaserScan
    topic: scan 
    marking: true
    clearing: true
    expected_update_rate: 0

range_sensor_layer:
  topics: ["/ultrasound0", "/ultrasound1", "/ultrasound2"]
  no_readings_timeout: 0.0
  clear_threshold: 0.2
  mark_threshold: 0.8
  clear_on_max_reading: true
