obstacle_range: 2.5
raytrace_range: 3.0
#robot_radius: 0.2
footprint: [[0.0,0.2], [0.35,0.2], [0.35,-0.2],[0,-0.2]]

max_obstacle_height: 0.6
min_obstacle_height: 0.0

obstacle_layer:
  observation_sources: laser_scan_sensor
  laser_scan_sensor:
    data_type: LaserScan
    topic: scan 
    marking: true
    clearing: true
    expected_update_rate: 0

