obstacle_range: 2.0
inflation_radius: 0.05
controller_frequency: 10.0
planner_frequency: 0.2

TrajectoryPlannerROS:
    max_vel_theta: 0.4
    min_vel_theta: -0.4


local_costmap:
    update_frequency: 5.0
    publish_frequency: 4.0
    resolution: 0.05
    #plugins:
    #  - {name: inflation_layer,  type: "costmap_2d::InflationLayer"}
    obstacle_layer:
      observation_sources: laser_scan_fusion_sensor
      laser_scan_fusion_sensor:
        data_type: LaserScan
        topic: laser_fusion
        marking: true
        clearing: true
        expected_update_rate: 0

global_costmap:
    resolution: 0.05
    update_frequency: 5.0
    publish_frequency: 4.0
    #plugins:
    #  - {name: inflation_layer,  type: "costmap_2d::InflationLayer"}

    obstacle_layer:
      observation_sources: laser_scan_fusion_sensor
      laser_scan_fusion_sensor:
        data_type: LaserScan
        topic: laser_fusion
        marking: true
        clearing: true
        expected_update_rate: 0

