## USB port
port: /dev/imu


##### Calibration ####
### accelerometer
accel_x_min: -267.0
accel_x_max: 255.0
accel_y_min: -254.0
accel_y_max: 253.0
accel_z_min: -274.0
accel_z_max: 237.0

### magnetometer
# standard calibration
magn_x_min: -332.0
magn_x_max: 766.0
magn_y_min: -614.0
magn_y_max: 643.0
magn_z_min: -646.0
magn_z_max: 524.0

# extended calibration
calibration_magn_use_extended: true
magn_ellipsoid_center: [-37.4176, -83.9335, 11.9836]
magn_ellipsoid_transform: [[0.954033, -0.0197249, 0.0122892], [-0.0197249, 0.977572, 0.0283469], [0.0122892, 0.0283469, 0.958587]]

# AHRS to robot calibration
imu_yaw_calibration: 0.0

### gyroscope
gyro_average_offset_x: -78.29
gyro_average_offset_y: 29.66
gyro_average_offset_z: -20.10
