obstacle_range: 1.5
inflation_radius: 0.25
robot_radius: 0.25
controller_frequency: 5.0

TrajectoryPlannerROS:
    max_vel_theta: 0.6
    min_vel_theta: -0.6
    min_in_place_vel_theta: 0.4


local_costmap:
    update_frequency: 5.0
    publish_frequency: 4.0
    resolution: 0.05
    #plugins:
    #  - {name: inflation_layer,  type: "costmap_2d::InflationLayer"}

global_costmap:
    resolution: 0.05
    update_frequency: 3.0
    publish_frequency: 2.0
